Feat/spawn npc from rviz
autowarefoundation/AWSIM-Labs pull request #118
Opened 2024-07-16 16:56 UTC by SujayAmberkar

## Description

- Will spawn NPC Pedestrians and Vehicles into the unity scene from Autoware.
- Velocity for the NPC vehicle can be specified in the ``Tool properties`` in Autoware under the ``2D Dummy Car/Bus``.
- Spawned NPCs will be deleted after a delay, which can be specified in the Unity Editor by changing the ``Despawn time``.
- RVIZNPCSpawner script is attached to the ``Environment`` game object.
![image](https://github.com/user-attachments/assets/46350a81-eb68-4a88-a9a1-c6e7fd0517c6)

### Related links

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-07-18 08:37 UTC, Aysenayilmaz approved these changes
I've tested with Autoware. There were no problems with the feature. I can spawn all objects and set the velocity in RViz.
https://youtu.be/_endo8zQhAo

2024-07-19 08:39 UTC, mozhoku requested changes

2024-07-19 08:39 UTC, mozhoku commented on Assets/AWSIM/Scripts/NPCs/RvizNPCSpawner/NPCMovement.cs
> +    }
LGTM, except this part: 

Calling` GetComponent()` (or similar methods) continuously in `Update()` function is a bad practice. Could you separate variables that needs to be updated only once?

Nice work!

2024-07-19 09:21 UTC, SujayAmberkar commented on Assets/AWSIM/Scripts/NPCs/RvizNPCSpawner/NPCMovement.cs
> +    }
@mozhoku Updated the code. Thank you!!

2024-07-19 09:50 UTC, mozhoku approved these changes

2024-07-19 09:52 UTC, merged