feat: add new pointcloud format
autowarefoundation/AWSIM-Labs pull request #122
Opened 2024-07-23 12:46 UTC by Aysenayilmaz

## Description
After updating the RobotecRGLLidar library, I've added the updated library and new script by cherry-picking from _**(@msz-rai)**_ the PR _(https://github.com/tier4/AWSIM/pull/334)_ opened in the [TierIV AWSIM](https://github.com/tier4/AWSIM) repo.  

I tried with Autoware main branch  and there is no problem with localization. 

### Related links

- https://github.com/autowarefoundation/autoware.universe/pull/6996
- https://github.com/autowarefoundation/AWSIM-Labs/issues/114
- https://github.com/RobotecAI/RobotecGPULidar/issues/313
- https://github.com/tier4/AWSIM/pull/334

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-07-23 14:32 UTC, xmfcx commented
Could you fix the precommit errors?
https://github.com/autowarefoundation/AWSIM-Labs/actions/runs/10059193737/job/27803894740?pr=122#step:5:115

2024-07-24 09:04 UTC, mozhoku requested changes

2024-07-24 09:04 UTC, mozhoku commented on ProjectSettings/ProjectSettings.asset
> +  allowUnsafeCode: 1
```suggestion
  allowUnsafeCode: 0
```

2024-07-24 09:06 UTC, mozhoku approved these changes

2024-07-24 09:07 UTC, mozhoku commented
It works with autoware-universe/main

LGTM :+1:

2024-07-24 09:19 UTC, merged

2024-10-28 13:16 UTC, xmfcx commented on Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormatLibrary.cs
> +                    RGLField.AZIMUTH_F32,
Order of these 2 lines should be changed.

2024-10-28 13:17 UTC, xmfcx commented on Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormatLibrary.cs
> +                {PointCloudFormat.PointXYZIRCEADT, new[]
PointXYZIRC**EA**DT -> PointXYZIRC**AE**DT

2024-10-28 13:18 UTC, xmfcx commented
Related:
- https://github.com/autowarefoundation/autoware.universe/issues/9020
- https://github.com/autowarefoundation/AWSIM-Labs/issues/173

2024-10-28 13:19 UTC, xmfcx commented on Assets/AWSIM/Scripts/Sensors/LiDAR/PointCloudFormatLibrary.cs
> +        PointXYZIRCEADT,
This too needs to be changed to `PointXYZIRCAEDT`

2024-10-28 13:19 UTC, xmfcx commented on Assets/AWSIM/Scripts/Sensors/LiDAR/RglLidarPublisher.cs
> +                fieldsPreset = PointCloudFormat.PointXYZIRCEADT,
This needs to be changed to `PointXYZIRCAEDT`