fix: missing parts
autowarefoundation/AWSIM-Labs pull request #161
Opened 2024-09-26 17:00 UTC by Aysenayilmaz

## Description

### Related links
https://github.com/autowarefoundation/AWSIM-Labs/issues/160 

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-09-27 05:32 UTC, mozhoku requested changes

2024-09-27 05:32 UTC, mozhoku commented on docs/GettingStarted/ParkingArea/index.md
> +    [Parking Are Map](https://drive.google.com/drive/folders/1ly8Z1_SQc9bJ834t_zKCyYSTyKJgj8ho)
@Aysenayilmaz Please make the links public. 
![image](https://github.com/user-attachments/assets/8a97c0a3-488f-4962-afdb-0a0335c8cd77)

I can't even open it with my work mail.

2024-09-27 05:58 UTC, xmfcx commented on docs/GettingStarted/ParkingArea/index.md
> +    [Parking Are Map](https://drive.google.com/drive/folders/1ly8Z1_SQc9bJ834t_zKCyYSTyKJgj8ho)
```suggestion
    [Parking Area Map](https://drive.google.com/drive/folders/1ly8Z1_SQc9bJ834t_zKCyYSTyKJgj8ho)
```

2024-09-30 10:24 UTC, mozhoku approved these changes

2024-09-30 10:25 UTC, merged