docs: update branding
autowarefoundation/AWSIM-Labs pull request #42
Opened 2024-04-15 12:11 UTC by mozhoku

## Description

This PR aims to enhance the documentation by explicitly stating that this repository is a **fork** of Tier IV's AWSIM repository. Naming it **AWSIM Labs**.
 
### Related links

- https://github.com/autowarefoundation/AWSIM/issues/35

## Tests performed

No tests performed.

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-04-15 21:51 UTC, xmfcx commented
For some reason I was not able to push to your branch.

Could you fast-forward this to https://github.com/autowarefoundation/AWSIM/tree/docs/update-branding

2024-04-15 22:14 UTC, xmfcx commented
Could you update the readme as well?

Could you also create a markdown table with feature differences from the upstream AWSIM?

2024-04-17 09:44 UTC, mozhoku commented
@xmfcx I've added table and updated the readme. Please let me know if you want any other changes.

2024-04-17 11:54 UTC, xmfcx requested changes

2024-04-17 11:54 UTC, xmfcx commented on README.md
> +![](docs/assets/images/awsim-labs-logo.png){: style="height:90px"}
This looks like this:
![Screenshot from 2024-04-17 14-50-36](https://github.com/autowarefoundation/AWSIM/assets/10751153/dfe19952-d26d-45c1-867d-1898604b4e46)

See: https://github.com/autowarefoundation/AWSIM/blob/e7054c0fb7a693b9a8e9975331330d7b6904cb7e/README.md

2024-04-17 11:54 UTC, xmfcx commented on README.md
> +[AWSIM Document - Quick Start Demo](https://autowarefoundation.github.io/AWSIM/main/GettingStarted/QuickStartDemo/)
```suggestion
[AWSIM Labs Documentation - Quick Start Demo](https://autowarefoundation.github.io/AWSIM/main/GettingStarted/QuickStartDemo/)
```

2024-04-17 11:54 UTC, xmfcx commented on README.md
> +see also [AWSIM document - Git branch](https://autowarefoundation.github.io/AWSIM/main/ProjectGuide/GitBranch/)
```suggestion
see also [AWSIM Labs Documentation - Git branch](https://autowarefoundation.github.io/AWSIM/main/ProjectGuide/GitBranch/)
```

2024-04-17 12:56 UTC, mozhoku commented on README.md
> +![](docs/assets/images/awsim-labs-logo.png){: style="height:90px"}
Okay, fixed it :+1:

2024-04-17 13:01 UTC, xmfcx commented on README.md
> +![](docs/assets/images/E2ESim.png)
```suggestion
![](docs/assets/images/E2ESim.png)
```

could you reduce the max size of this too?

2024-04-17 13:03 UTC, xmfcx commented
![brave_EOtTN5nbsq](https://github.com/autowarefoundation/AWSIM/assets/10751153/5b7aa5c6-a602-471e-a29e-e5103cc0c84c)

Please update these to AWSIM Labs too.

2024-04-17 13:44 UTC, mozhoku commented on README.md
> +![](docs/assets/images/E2ESim.png)
Do you have a specific value for max size in your mind or should I set it whatever value I have in my mind?

2024-04-17 14:11 UTC, xmfcx commented on mkdocs.yml
> +site_name: AWSIM Labs document
```suggestion
site_name: AWSIM Labs Documentation
```

2024-04-17 14:13 UTC, xmfcx commented on README.md
> +<img src="docs/assets/images/E2ESim.png" width="640" height="360">
```suggestion
<img src="docs/assets/images/E2ESim.png" height="200">
```

2024-04-17 14:16 UTC, xmfcx commented
Can you remove https://github.com/autowarefoundation/AWSIM/tree/main/README_img too since now it is unused?

2024-04-17 15:10 UTC, mozhoku commented on README.md
> +<img src="docs/assets/images/E2ESim.png" width="640" height="360">
Done in: https://github.com/autowarefoundation/AWSIM/pull/42/commits/e40ca28813972a7f960d640e20f062376f1ac62b

2024-04-17 15:30 UTC, xmfcx approved these changes

2024-04-17 15:32 UTC, merged