add: slider for adjusting traffic density
autowarefoundation/AWSIM-Labs pull request #67
Opened 2024-05-05 18:16 UTC by mozhoku

## Description

This PR adds a slider to the UI for adjusting the traffic density.

### Related links
 
- https://github.com/autowarefoundation/AWSIM/issues/64

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-05-07 14:06 UTC, mozhoku commented
Demonstration:

- https://youtu.be/zH2sNbivYlo

2024-05-09 12:56 UTC, xmfcx commented on Assets/AWSIM/Scripts/RandomTraffic/TrafficManager.cs
> +        public int targetVehicleCount = 10;
```suggestion
        public int MaxVehicleCount = 100;
        public int TargetVehicleCount = 10;
```

2024-05-09 12:57 UTC, xmfcx commented on Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
> +        [SerializeField] private Text textField;
```suggestion
        [SerializeField] private Text _textField;
```

2024-05-09 12:57 UTC, xmfcx requested changes
Some naming guideline suggestions.

2024-05-09 13:17 UTC, mozhoku commented on Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
> +        [SerializeField] private Text textField;
Rider does not suggests "_" prefix to the "[SerializeField] private xxx yyyy" variables

2024-05-09 13:22 UTC, xmfcx commented on Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
> +        [SerializeField] private Text textField;
https://docs.unity3d.com/Manual/script-Serialization.html

Unity treats them same as private members. So apply the underscore please.

Rider probably learns the conventions from the code itself.

2024-05-09 13:24 UTC, mozhoku commented on Assets/AWSIM/Scripts/RandomTraffic/TrafficManager.cs
> +        public int targetVehicleCount = 10;
https://github.com/autowarefoundation/AWSIM/pull/67/commits/b82e26297e8469efed2120089ac58232b32e2f67

2024-05-09 13:25 UTC, mozhoku commented on Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs
> +        [SerializeField] private Text textField;
https://github.com/autowarefoundation/AWSIM/pull/67/commits/65bfe1d54f9f629c3c9b3f3bcac2a2e6be23cf61

2024-05-09 15:09 UTC, xmfcx commented
https://github.com/autowarefoundation/AWSIM/assets/10751153/c89f2a14-b0a7-4553-93d6-2e566abef391

```
NullReferenceException: Object reference not set to an instance of an object
AWSIM.Scripts.UI.UITrafficVehicleDensity.TrafficManagerSetTargetVehicleCount () (at Assets/AWSIM/Scripts/UI/UITrafficVehicleDensity.cs:27)
UnityEngine.Events.InvokableCall.Invoke () (at /home/bokken/build/output/unity/unity/Runtime/Export/UnityEvent/UnityEvent.cs:178)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at /home/bokken/build/output/unity/unity/artifacts/generated/UnityEvent/UnityEvent_1.cs:62)
UnityEngine.UI.Slider.Set (System.Single input, System.Boolean sendCallback) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Slider.cs:540)
UnityEngine.UI.Slider.set_value (System.Single value) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Slider.cs:267)
UnityEngine.UI.Slider.set_normalizedValue (System.Single value) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Slider.cs:314)
UnityEngine.UI.Slider.UpdateDrag (UnityEngine.EventSystems.PointerEventData eventData, UnityEngine.Camera cam) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Slider.cs:623)
UnityEngine.UI.Slider.OnDrag (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Slider.cs:657)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IDragHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:78)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
```

2024-05-09 15:16 UTC, mozhoku commented
@xmfcx After renaming the SerializedField, reference is lost. Should be okay now.

2024-05-09 15:29 UTC, xmfcx commented
https://github.com/autowarefoundation/AWSIM/assets/10751153/a5db774d-5c21-4947-a72d-fdc23cc0ff0c

It works :+1:

2024-05-09 16:10 UTC, xmfcx approved these changes

2024-05-09 16:12 UTC, merged