fix: null reference errors
autowarefoundation/AWSIM-Labs pull request #78
Opened 2024-05-23 09:15 UTC by mozhoku

## Description

Fixes null reference exception errors when selecting the scene prefab. 
Caused by TrafficLaneEditor.cs.
Added a null check as a fix.
### Related links

- https://github.com/autowarefoundation/AWSIM/issues/77

## Tests performed

Tested in editor.
## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-05-23 11:58 UTC, xmfcx commented on Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/TrafficLaneEditor.cs
> +                    continue;
Could you add a simple warning log here as it continues?

2024-05-23 11:59 UTC, xmfcx requested changes
We should add logs for null occurrence in there.

2024-05-23 12:45 UTC, mozhoku commented on Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/TrafficLaneEditor.cs
> +                    continue;
Even if I add a log there, it will flood the editor console with warnings.

2024-05-23 14:19 UTC, xmfcx commented on Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/TrafficLaneEditor.cs
> +                    continue;
This is fine and necessary, the source of the problems should be eliminated instead of masking them.

2024-05-24 08:11 UTC, mozhoku commented on Assets/AWSIM/Scripts/Editor/RandomTraffic/Environments/TrafficLaneEditor.cs
> +                    continue;
https://github.com/autowarefoundation/AWSIM-Labs/pull/78/commits/351aadab11ef5192542446eb1c36a45ef7a990f2

2024-05-24 08:28 UTC, xmfcx approved these changes

2024-05-24 09:34 UTC, merged