docs: update feature added in AWSIM-Labs
autowarefoundation/AWSIM-Labs pull request #90
Opened 2024-06-05 16:07 UTC by mitsudome-r

## Description
The current table makes it look like AWSIM is worse than AWSIM-Labs with a lot of `X`, but I don't think it is fair to make such comparison if you are making modification on top of fork.

I would like to modify the documentation to show some respect to the upstream developers as well.

### Related links
N/A

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-06-05 17:26 UTC, mitsudome-r commented
NOTE from the discussion with Fatih: 
We are planning to move this table to Autoware Documentation. There we will have both AWSIM-Labs and TIER IV's AWSIM team to update the table to show the difference between the two.

We can merge this PR once we create the table in Autoware Documentation.

2024-06-16 13:09 UTC, xmfcx requested changes

2024-06-16 13:09 UTC, xmfcx commented on docs/index.md
```suggestion

### Feature differences from the TIER IV/AWSIM

See [Feature differences from the TIER IV/AWSIM in the Autoware Documentation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial/#feature-differences-from-the-awsim-and-awsim-labs).
```

2024-06-16 13:10 UTC, xmfcx commented
You also need to update the [README.md](https://github.com/autowarefoundation/AWSIM-Labs?tab=readme-ov-file#feature-differences-from-the-tier-ivawsim) section with the new text:

```
See [Feature differences from the TIER IV/AWSIM in the Autoware Documentation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial/#feature-differences-from-the-awsim-and-awsim-labs).
```

2024-07-02 11:53 UTC, xmfcx commented
@mozhoku could you take over this task?

2024-07-02 12:00 UTC, xmfcx commented on docs/index.md
> +See [Feature differences from the TIER IV/AWSIM in the Autoware Documentation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/aws
```suggestion
See [Feature differences from the TIER IV/AWSIM in the Autoware Documentation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial/#feature-differences-from-the-awsim-and-awsim-labs).

```

2024-07-02 12:55 UTC, xmfcx commented
Closing for:
- https://github.com/autowarefoundation/AWSIM-Labs/pull/98

2024-07-02 12:55 UTC, closed without merging